#!/bin/bash

source /GPUFS/sysu_hpcedu_302/asc21/WuK/spack/share/spack/setup-env.sh
spack unload -a
spack load gcc@7.5.0%gcc@4.8.5
spack load autoconf@2.69%gcc@7.5.0
spack load autoconf-archive@2019.01.06%gcc@7.5.0
spack load automake@1.16.3%gcc@7.5.0
spack load openmpi@4.0.5%gcc@7.5.0
spack load blaspp@2020.10.02%gcc@7.5.0
autoreconf -ivf
./configure \
    CPPFLAGS="-DHPL_CALL_CBLAS -DHPL_DETAILED_TIMING -DHPLAI_IR_PARA"
make -j
if true; then
    cp testing/ptest/HPL.dat HPL.dat
else
    echo 'HPLinpack benchmark input file
Innovative Computing Laboratory, University of Tennessee
HPL.out      output file name (if any)
6            device out (6=stdout,7=stderr,file)
1            # of problems sizes (N)
25000 30000 40000 50000 60000 39007 39000  20960 364160 359424 276480 138240 115200 23040 354432 236160 95040 9600 20737 16129 16128 Ns
1             # of NBs
384 768 1024 512 384 640 768 896 960 1024 1152 1280 384 640 960 768 640 256  960 512 768 1152         NBs
0            PMAP process mapping (0=Row-,1=Column-major)
1            # of process grids (P x Q)
2 1 4        Ps
2 4 1        Qs
16.0         threshold
1            # of panel fact
0 1 2        PFACTs (0=left, 1=Crout, 2=Right)
1            # of recursive stopping criterium
2 8          NBMINs (>= 1)
1            # of panels in recursion
2            NDIVs
1            # of recursive panel fact.
0 1 2        RFACTs (0=left, 1=Crout, 2=Right)
1            # of broadcast
0 2          BCASTs (0=1rg,1=1rM,2=2rg,3=2rM,4=Lng,5=LnM)
1            # of lookahead depth
1 0          DEPTHs (>=0)
1            SWAP (0=bin-exch,1=long,2=mix)
192          swapping threshold
1            L1 in (0=transposed,1=no-transposed) form
1            U  in (0=transposed,1=no-transposed) form
1            Equilibration (0=no,1=yes)
8            memory alignment in double (> 0)' >HPL.dat
fi
mpiexec -n 4 -x OMP_NUM_THREADS=7 testing/xhpl
mpiexec -n 4 -x OMP_NUM_THREADS=7 testing/xhplai
git clean -d -f -q -x
